logging:
  pattern:
    console: "${LOGGER_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}}"

server:
    port: 9000
spring:
  application:
    name: loans
#  profiles:
#    active: prod
  datasource:
    url: jdbc:h2:mem:loansdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  show-sql: true
  config:
    import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true #to enable info details for an actuator

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true #register with ip address but not with hostname because there is not any DNS mappings provided
  client:
    fetchRegistry: true #fetch registered services
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: loans
    description: Microservicesbank Loans microservice
    version: 4