accounts:
  message: Welcome to Microservices Bank Accounts for production
  contactDetails:
    name: Andrii Kuchera - Product Owner
    email: andrii@example.com
  onCallSupport:
    - (555) 367-2357
    - (555) 777-7777