server:
    port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: accountCreatedEmail|accountCreatedSms;accountDeletedEmail|accountDeletedSms
    stream:
      bindings:
        accountCreatedEmail|accountCreatedSms-in-0:
          destination: created-account
          group: ${spring.application.name}
        accountCreatedEmail|accountCreatedSms-out-0:
          destination: created-notification-sent
        accountDeletedEmail|accountDeletedSms-in-1:
          destination: deleted-account
          group: ${spring.application.name}
        accountDeletedEmail|accountDeletedSms-out-1:
          destination: deleted-notification-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s
