server:
    port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms #function to be invoked while processing emailsms-in-0,
                            #they are processing simultaneously but final result is the one from the last function
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
