deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
    repository: akuchera/loans
    tag: k8s.0

containerPort: 9000

service:
    type: ClusterIP
    port: 9000
    targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
rabbitmq_enabled: true

